CREATE TABLE notices_new (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    subheading VARCHAR(255),
    content TEXT NOT NULL,
    posted_by VARCHAR(255) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    attachment_path VARCHAR(255),
    attachment_type VARCHAR(50)
); 